micronaut:
  application:
    name: tournaments-overlay
  router:
    static-resources:
      default:
        enabled: true
        mapping: /static/**
        paths: classpath:static
      webjars:
        paths: classpath:META-INF/resources/webjars
        mapping: /webjars/**
  views:
    thymeleaf:
      enabled: true
      prefix: classpath:views/
      suffix: .html
      template-mode: HTML
      encoding: UTF-8
      template-resolver:
        prefix: classpath:views/
        suffix: .html
        template-mode: HTML
        cache: false
      cache: false
  server:
    thread-selection: AUTO
    netty:
      event-loops:
        default:
          num-threads: 8
# Development-specific settings
---
micronaut:
  environments: development
  views:
    thymeleaf:
      cache: false
      template-resolver:
        cache: false
        cacheable: false
  server:
    restart:
      enabled: true
      paths:
        - src/main/resources/views
        - src/main/resources/static
    development: true
apollo:
  schema-file-path: schema.json
graphql:
  endpoint: https://api.start.gg/gql/alpha
  token: ${GRAPHQL_TOKEN}
jackson:
  serialization-inclusion: ALWAYS